### PR TITLE
S3 Build & Deployment

### PR DESCRIPTION
**Pull request by wcandillon**
fixes #22

### CODE REVIEW

**Comment by Alexander-Kreutz** [comment]
Does not seem to work if no TRAVIS_SECRET_KEY is set, but
the credentials.json is manually created.

**Comment by wcandillon** [comment]
can you elaborate? travis seems to execute the steps properly.

**Comment by Alexander-Kreutz** [comment]
It fails if I run "gulp" locally. It complains about the TRAVIS_SECRET_KEY not set or corrupts the config file if I just set the variable to something.

**Comment by wcandillon** [comment]
This behavior makes sense right?

**Comment by wcandillon** [comment]
Implemented review comments. Alexander authorized me to merge it.

**Pull request merged**
