### PR TITLE
Filterpage

### LINKED ISSUE #18: Order the concepts by used attribute

### LINKED ISSUE #19: Update filter page
- Remove the Entity part of the filter
- Add select for fiscal year
- Fiscal year should be before fiscal period

### LINKED ISSUE #20: Add filter in the URL using query parameters
Changing the query parameter shouldn't reload the whole view.

### PR DESCRIPTION
**Pull request by Alexander-Kreutz**
fixes #18
fixes #19 
fixes #20

### CODE REVIEW

**Comment by wcandillon** [comment]
@Alexander-Kreutz All doesn't seem to work for entity group. Are you able to reproduce it?

**Comment by wcandillon** [comment]
@Alexander-Kreutz Clicking on a concept, seems to refresh the left sidebar. Because the value is not "cached" I assume. Then I cannot go any further, maybe because of the backend issue you mentioned.

**Comment by Alexander-Kreutz** [comment]
@wcandillon "All" does not work because of the second issue I wrote.

**Comment by wcandillon** [comment]
@Alexander-Kreutz Great stuff.

**Comment by wcandillon** [comment]
The following query

```
http://secxbrl.28.io/v1/_queries/public/api/facts.jq?aid=0000858877-14-000029&concept=disc:AdvertisingCostsPolicyTextBlock&fiscalPeriod=FY&fiscalYear=2014&map=Disclosures&token=becd3d60-d470-446e-8b5a-b6d6e4391331
```

Throws a 500 (cc @dknochen @gislenius)

**Pull request merged**
